//
// Generated file, do not edit! Created by nedtool 5.6 from apps/mecRequestResponseApp/packets/MigrationTimer.msg.
//

#ifndef __MIGRATIONTIMER_M_H
#define __MIGRATIONTIMER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class MigrationTimer;
/**
 * Class generated from <tt>apps/mecRequestResponseApp/packets/MigrationTimer.msg:14</tt> by nedtool.
 * <pre>
 * message MigrationTimer
 * {
 *     unsigned int oldAppId;
 *     unsigned int newAppId;
 * }
 * </pre>
 */
class MigrationTimer : public ::omnetpp::cMessage
{
  protected:
    unsigned int oldAppId = 0;
    unsigned int newAppId = 0;

  private:
    void copy(const MigrationTimer& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MigrationTimer&);

  public:
    MigrationTimer(const char *name=nullptr, short kind=0);
    MigrationTimer(const MigrationTimer& other);
    virtual ~MigrationTimer();
    MigrationTimer& operator=(const MigrationTimer& other);
    virtual MigrationTimer *dup() const override {return new MigrationTimer(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getOldAppId() const;
    virtual void setOldAppId(unsigned int oldAppId);
    virtual unsigned int getNewAppId() const;
    virtual void setNewAppId(unsigned int newAppId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MigrationTimer& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MigrationTimer& obj) {obj.parsimUnpack(b);}

#endif // ifndef __MIGRATIONTIMER_M_H

