//
// Generated file, do not edit! Created by nedtool 5.6 from common/LteCommon.msg.
//

#ifndef __LTECOMMON_M_H
#define __LTECOMMON_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "common/LteCommon.h"
// }}

#endif // ifndef __LTECOMMON_M_H

