//
// Generated file, do not edit! Created by nedtool 5.6 from modules/communication/NR/App/WirelessAppPacket.msg.
//

#ifndef __WIRELESSAPPPACKET_M_H
#define __WIRELESSAPPPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class WirelessAppPacket;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/common/geometry/Geometry_m.h" // import inet.common.geometry.Geometry

// cplusplus {{
    #include "util/DataTypes/StateDataTypes.h" 
    #include "modules/vehicle/CommunicationCoordinator.h"        
// }}

/**
 * Class generated from <tt>modules/communication/NR/App/WirelessAppPacket.msg:31</tt> by nedtool.
 * <pre>
 * class WirelessAppPacket extends inet::FieldsChunk
 * {
 *     simtime_t payloadTimestamp;
 *     StateWithCovariance AgentLocation;
 *     double num;
 * 
 * }
 * </pre>
 */
class WirelessAppPacket : public ::inet::FieldsChunk
{
  protected:
    omnetpp::simtime_t payloadTimestamp = SIMTIME_ZERO;
    StateWithCovariance AgentLocation;
    double num = 0;
    string encodedImage = "";

  private:
    void copy(const WirelessAppPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const WirelessAppPacket&);

  public:
    WirelessAppPacket();
    WirelessAppPacket(const WirelessAppPacket& other);
    virtual ~WirelessAppPacket();
    WirelessAppPacket& operator=(const WirelessAppPacket& other);
    virtual WirelessAppPacket *dup() const override {return new WirelessAppPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual omnetpp::simtime_t getPayloadTimestamp() const;
    virtual void setPayloadTimestamp(omnetpp::simtime_t payloadTimestamp);
    virtual const StateWithCovariance& getAgentLocation() const;
    virtual StateWithCovariance& getAgentLocationForUpdate() { handleChange();return const_cast<StateWithCovariance&>(const_cast<WirelessAppPacket*>(this)->getAgentLocation());}
    virtual void setAgentLocation(const StateWithCovariance& AgentLocation);
    virtual void setImage(string encodedImage);
    virtual string getImage() const;
    virtual double getNum() const;
    virtual void setNum(double num);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WirelessAppPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WirelessAppPacket& obj) {obj.parsimUnpack(b);}

#endif // ifndef __WIRELESSAPPPACKET_M_H

